Repository node-oauth/node-oauth2-server, pull requests merged in 2022-10, with the labels that each got.

#164 docs: add badges to README #163
  README.md
Labels: documentation :bookmark_tabs:, hacktoberfest

#168 Ci update core actions
  .github/workflows/tests-release.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  docs/misc/extension-grants.rst
  package.json
Labels: hacktoberfest

#161 Save code challenge with authorization code
  index.d.ts
  lib/handlers/authorize-handler.js
  test/integration/handlers/authorize-handler_test.js
  test/unit/handlers/authorize-handler_test.js
Labels: compliance :scroll:
